rm(list=ls())
library(org.Mm.eg.db)
library(org.Hs.eg.db)
library(clusterProfiler)
setwd("F:\\02.employment\\03.tRNA\\15.rnaseq")
data_1 <- read.table("tRNA_gene.txt")
data_2 <- bitr(data_1$V1, fromType = "SYMBOL",toType = "ENTREZID",OrgDb = org.Hs.eg.db)
write.csv(data_2,file = "human_relatedgene.csv")
data_3 <- bitr(data_1$V1, fromType = "SYMBOL",toType = "ENTREZID",OrgDb = org.Mm.eg.db)
write.csv(data_3,file = "mouse_relatedgene.csv")