rm(list = ls())
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggplot2)
require(plyr)
setwd("E:\\temp\\06.trna\\03.WSN\\02.ctl_wsn_heatmap\\03.aa")
## Read count table, which is generated by the featureCount function from subread software
data <- read.csv("ctl_wsn_aa zscore.csv", header=T, row.names = 1)
# data$fc <- log2(data$fc)
# data$fc <- replace(data$fc, data$fc == -Inf, 0)
# data$fc <- ifelse(is.na(data$fc), 0, data$fc)
# exp1 <- data[,1:2]
# exp1 <- exp1*10
# bk <- seq(0,10,by=0.1)
bk <- c(seq(-1,-0.1,by=0.1),seq(0,1,by=0.1))
p=pheatmap(data,
           show_rownames = T,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='IC and CTL name expression zscore.pdf',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=8,  #输出图片的高度
           width =6,
           # scale = "row",
           angle_col=45, #调整字的角度
           # color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                    colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           legend_breaks=seq(-1,1,1),
           breaks=bk,
           clustering_distance_rows = 'correlation',
           clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)

p=pheatmap(data,
           show_rownames = T,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='IC and CTL name expression zscore.tiff',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=8,  #输出图片的高度
           width =6,
           # scale = "row",
           angle_col=45, #调整字的角度
           # color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                    colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           legend_breaks=seq(-1,1,1),
           breaks=bk,
           clustering_distance_rows = 'correlation',
           clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)

p=pheatmap(data,
           show_rownames = F,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='IC and CTL expression zscore.tiff',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=8,  #输出图片的高度
           width =6,
           # scale = "row",
           angle_col=45, #调整字的角度
           # color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                    colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           legend_breaks=seq(-1,1,1),
           breaks=bk,
           clustering_distance_rows = 'correlation',
           clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)
p=pheatmap(data,
           show_rownames = F,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='IC and CTL expression zscore.pdf',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=8,  #输出图片的高度
           width =6,
           # scale = "row",
           angle_col=45, #调整字的角度
           # color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                    colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           legend_breaks=seq(-1,1,1),
           breaks=bk,
           clustering_distance_rows = 'correlation',
           clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)

bk <- c(seq(-1,-0.1,by=0.1),seq(0,1,by=0.1))

exp3 <- data.frame(scale(exp1,center = TRUE))
p=pheatmap(exp1,
           show_rownames = T,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='IC and CTL name expression zscore.tiff',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=70,  #输出图片的高度
           width =10,
           scale = "row",
           angle_col=45, #调整字的角度
           # color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                    colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           legend_breaks=seq(-1,1,0.5),
           breaks=bk,
           clustering_distance_rows = 'correlation',
           clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)
p=pheatmap(exp3,
           show_rownames = T,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='IC and CTL name expression zscore.pdf',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=70,  #输出图片的高度
           width =10,
           # scale = "row",
           angle_col=45, #调整字的角度
           # color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                    colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           legend_breaks=seq(-1,1,0.5),
           breaks=bk,
           clustering_distance_rows = 'correlation',
           clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)
p=pheatmap(exp3,
           show_rownames = F,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='IC and CTL expression zscore.pdf',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=70,  #输出图片的高度
           width =10,
           # scale = "row",
           angle_col=45, #调整字的角度
           # color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                    colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           legend_breaks=seq(-1,1,0.5),
           breaks=bk,
           clustering_distance_rows = 'correlation',
           clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)
p=pheatmap(exp3,
           show_rownames = F,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='IC and CTL expression zscore.tiff',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=70,  #输出图片的高度
           width =10,
           # scale = "row",
           angle_col=45, #调整字的角度
           # color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                    colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           legend_breaks=seq(-1,1,0.5),
           breaks=bk,
           clustering_distance_rows = 'correlation',
           clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)



# rowdata=rownames(exp1[p$tree_row[["order"]],])
# write.table(rowdata,file='rowdata.txt', row.names=F, col.names = F, quote=F)
cols <- c("fc")
exp2 <- data[, cols, drop=FALSE]
colnames(exp2) <- "log2foldchange"
bk <- c(seq(-4,-0.1,by=0.1),seq(0,4,by=0.1))
# exp3=exp2[match(rowdata, rownames(exp2)), ]
# exp3=data.frame(rowdata,exp3)
# rownames(exp3)<-exp3[,1] 
# cols <- c("exp3")
# exp4 <- exp3[, cols, drop=FALSE]
# colnames(exp4) <- c("PIC versus CTL")
P3=pheatmap(exp2,
            show_rownames = T,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='IC versus CTL name expression.tiff',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=70,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                     colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
            legend_breaks=seq(-4,4,2),
            breaks=bk,
            clustering_distance_rows = 'correlation',
            clustering_method = 'single',
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)

P3=pheatmap(exp2,
            show_rownames = T,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='IC versus CTL name expression.pdf',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=70,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                     colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
            legend_breaks=seq(-4,4,2),
            breaks=bk,
            clustering_distance_rows = 'correlation',
            clustering_method = 'single',
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)
P3=pheatmap(exp2,
            show_rownames = F,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='IC versus CTL expression.pdf',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=70,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                     colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
            legend_breaks=seq(-4,4,2),
            breaks=bk,
            clustering_distance_rows = 'correlation',
            clustering_method = 'single',
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)
P3=pheatmap(exp2,
            show_rownames = F,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='IC versus CTL expression.tiff',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=70,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                     colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
            legend_breaks=seq(-4,4,2),
            breaks=bk,
            clustering_distance_rows = 'correlation',
            clustering_method = 'single',
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)

