rm(list = ls())
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggplot2)
require(plyr)
library(dplyr)
setwd("G:\\temp\\06.trna\\07.zhang\\results")
## Read count table, which is generated by the featureCount function from subread software
data <- read.table("ctrmock_ctrinfected_expression_isoaccpter.txt",header = TRUE)
data$FC <- log2(data$FC)
data$FC <- replace(data$FC, data$FC == -Inf, 0)
data$FC <- ifelse(is.na(data$FC), 0, data$FC)
exp1 <- data[,1:2]

p=pheatmap(exp1,
           show_rownames = T,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='ctrmock_ctrinfected_expression_isoaccpter_name_scale.pdf',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=70,  #输出图片的高度
           width =10,
           scale = "row",
           angle_col=45, #调整字的角度
           color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           # color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
           #          colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           # legend_breaks=seq(0,10,2),
           # breaks=bk,
           # clustering_distance_rows = 'correlation',
           # clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)

p=pheatmap(exp1,
           show_rownames = F,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='ctrmock_ctrinfected_expression_isoaccpter_scale.pdf',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=70,  #输出图片的高度
           width =10,
           scale = "row",
           angle_col=45, #调整字的角度
           color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           # color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
           #          colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           # legend_breaks=seq(0,10,2),
           # breaks=bk,
           # clustering_distance_rows = 'correlation',
           # clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)
p=pheatmap(exp1,
           show_rownames = T,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='ctrmock_ctrinfected_expression_isoaccpter_name_noscale.pdf',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=70,  #输出图片的高度
           width =10,
           angle_col=45, #调整字的角度
           color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           # color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
           #          colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           # legend_breaks=seq(0,10,2),
           # breaks=bk,
           # clustering_distance_rows = 'correlation',
           # clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)

p=pheatmap(exp1,
           show_rownames = F,
           show_colnames = T,
           cluster_cols = F,
           cluster_rows=F,
           treeheight_row=50,
           filename='ctrmock_ctrinfected_expression_isoaccpter_noscale.pdf',#输出文件的名称
           fontsize_row=15, #行字体的大小
           fontsize=20,
           height=70,  #输出图片的高度
           width =10,
           angle_col=45, #调整字的角度
           color =colorRampPalette(c("#0000FF", "white","#CC0000"))(100),
           # color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
           #          colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
           # legend_breaks=seq(0,10,2),
           # breaks=bk,
           # clustering_distance_rows = 'correlation',
           # clustering_method = 'single',
           cellwidth = 40,
           cellheight = 17,
           border=F,
           # gaps_col = c(2, 3),
           border_color="white",
           # display_numbers = TRUE
)

####log2fc
cols <- c("FC")
exp2 <- data[, cols, drop=FALSE]
colnames(exp2) <- "log2foldchange"
exp2_sorted <- exp2 %>% arrange(desc(log2foldchange))
custom_color <- colorRampPalette(c("blue", "white", "red"))(100)
font_size <- 20
paletteLength <- 50
myColor <- colorRampPalette(c("blue", "white", "red"))(paletteLength)
myBreaks <- c(seq(min(exp2_sorted), 0, length.out=ceiling(paletteLength/2) + 1), 
              seq(max(exp2_sorted)/paletteLength, max(exp2_sorted), length.out=floor(paletteLength/2)))

P1=pheatmap(exp2_sorted,
            show_rownames = T,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='ctrmock_ctrinfected_expression_isoaccpter_log2fc_name.pdf',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=70,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =myColor,
            breaks = myBreaks,
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)


P1=pheatmap(exp2_sorted,
            show_rownames = F,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='ctrmock_ctrinfected_expression_isoaccpter_log2fc.pdf',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=70,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =myColor,
            breaks = myBreaks,
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)


####zscore 自造
data_zscore <- read.csv("BMDM_CTR_PIC_isoaccepter_zscore.csv", header=T, row.names = 1)
bk <- c(seq(-1,-0.1,by=0.1),seq(0,1,by=0.1))
P2=pheatmap(data_zscore,
            show_rownames = T,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='zscore name expression.tiff',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=15,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                     colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
            legend_breaks=seq(-1,1,0.5),
            breaks=bk,
            clustering_distance_rows = 'correlation',
            clustering_method = 'single',
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)

P2=pheatmap(data_zscore,
            show_rownames = T,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='zscore name expression.pdf',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=15,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                     colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
            legend_breaks=seq(-1,1,0.5),
            breaks=bk,
            clustering_distance_rows = 'correlation',
            clustering_method = 'single',
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)
P2=pheatmap(data_zscore,
            show_rownames = F,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='zscore expression.pdf',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=15,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                     colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
            legend_breaks=seq(-1,1,0.5),
            breaks=bk,
            clustering_distance_rows = 'correlation',
            clustering_method = 'single',
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)
P2=pheatmap(data_zscore,
            show_rownames = F,
            show_colnames = T,
            cluster_cols = F,
            cluster_rows=F,
            treeheight_row=50,
            filename='zscore expression.tiff',#输出文件的名称
            fontsize_row=15, #行字体的大小
            fontsize=20,
            height=15,  #输出图片的高度
            width =10,
            # scale = "row",
            angle_col=45, #调整字的角度
            color =c(colorRampPalette(c("#0000FF", "white"))(length(bk)/2),
                     colorRampPalette(colors = c("white","#CC0000"))(length(bk)/2)),
            legend_breaks=seq(-1,1,0.5),
            breaks=bk,
            clustering_distance_rows = 'correlation',
            clustering_method = 'single',
            cellwidth = 40,
            cellheight = 15,
            border=F,
            # gaps_col = c(2, 3),
            border_color="white"
)

