rm(list = ls())
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggplot2)
require(plyr)
library(edgeR)

setwd("E:\\temp\\06.trna\\02.result\\result\\trna_abundance\\03.aa")
## Read count table, which is generated by the featureCount function from subread software
data <- read.table("all_nomt_aa.txt",header = T,row.names = 1)
data_1 <- round(data*1000)
## make DESeq dataset
col.data = data.frame(Sample = rep(c("control","polyic"), c(2,2)))
dds <- DESeqDataSetFromMatrix(countData = data_1, colData = col.data, design = ~ Sample)
# ## Get normalized counts
# dir.create("./correlation")
# setwd("./correlation")
# dds <- estimateSizeFactors(dds)
# dds.cnt.nrm = counts(dds, normalized = TRUE)
# write.table(dds.cnt.nrm, file="merged_count.normalized.txt", sep="\t", quote=FALSE, row.names = TRUE, col.names = TRUE)
# ## Correlation_heatmap
# dds.cnt.nrm.l10 = log10(dds.cnt.nrm+1)
# tiff(file="Correlation_heatmap.tiff",width=20,height = 20,units = "cm", compression = "lzw",bg="white",res=600)
# pheatmap(cor(dds.cnt.nrm.l10, method = "p"), 
#          color = colorRampPalette(c("light pink","white","purple"))(50),
#          cluster_rows = FALSE, cluster_cols = FALSE,
#          display_numbers = TRUE, number_format = "%.3f")
# dev.off()
# pdf(file="Correlationheatmap.pdf",width=5,height = 5)
# pheatmap(cor(dds.cnt.nrm.l10, method = "p"), 
#          color = colorRampPalette(c("light pink","white","purple"))(50),
#          cluster_rows = FALSE, cluster_cols = FALSE,
#          display_numbers = TRUE, number_format = "%.3f")
# 
# dev.off()
# 
# 
# 
# ## PCA analysis
# rld <- rlog(dds, blind = TRUE)
# pca.rld.data <- plotPCA(rld, intgroup = c("Sample"),returnData = TRUE, ntop = 1000)
# percent.rld.var = round(100*attr(pca.rld.data, "percentVar"))
# pdf(file="PCA.pdf",width=5,height = 5)
# ggplot(pca.rld.data, aes(PC1, PC2, color=Sample)) +
#   theme_bw() + 
#   xlim(-90,90) + ylim(-30, 30) +
#   geom_point(size = 4) +
#   geom_text(aes(label=name),hjust=-0.5, vjust=0.4) +
#   xlab(paste0("PC1: ", percent.rld.var[1], "% variance")) +
#   ylab(paste0("PC2: ", percent.rld.var[2], "% variance"))
# dev.off()
# tiff(file="PCA.tiff",width=20,height = 20,units = "cm", compression = "lzw",bg="white",res=600)
# ggplot(pca.rld.data, aes(PC1, PC2, color=Sample)) +
#   theme_bw() + 
#   xlim(-90,90) + ylim(-30, 30) +
#   geom_point(size = 4) +
#   geom_text(aes(label=name),hjust=-0.5, vjust=0.4) +
#   xlab(paste0("PC1: ", percent.rld.var[1], "% variance")) +
#   ylab(paste0("PC2: ", percent.rld.var[2], "% variance"))
# dev.off()
####### DE analysis  ########
dir.create("../deseq2")
setwd("../deseq2")
design(dds) = ~Sample
dds = DESeq(dds)
res  = results(dds, contrast = c("Sample", "polyic","control"))
write.csv(res,file = "DEanalysis.csv")

# Get DEGs
up.lst <- row.names(res[!is.na(res$log2FoldChange) & !is.na(res$padj) & res$log2FoldChange > 0 & res$padj < 0.05,])
dn.lst <- row.names(res[!is.na(res$log2FoldChange) & !is.na(res$padj) & res$log2FoldChange < 0 & res$padj < 0.05,])
length(up.lst)
length(dn.lst)
write.table(sub(":.*$","",up.lst), file="DEGs_Up.ENSEMBL_ID.txt", row.names = FALSE, col.names = FALSE, sep = "\t", quote = FALSE)
write.table(sub(":.*$","",dn.lst), file="DEGs_Down.ENSEMBL_ID.txt", row.names = FALSE, col.names = FALSE, sep = "\t", quote = FALSE)
# Sort by p-value
res.srt = res[order(res$pvalue),]
write.csv(res.srt, file = "DE_sorted.csv")
write.csv(res[!is.na(res$log2FoldChange) & !is.na(res$padj) & res$log2FoldChange > 0 & res$padj < 0.05,], file = "DEGs_Up_sorted.csv")
write.csv(res[!is.na(res$log2FoldChange) & !is.na(res$padj) & res$log2FoldChange < 0 & res$padj < 0.05,], file = "DEGs_down_sorted.csv")
de.lst = unique(c(up.lst,dn.lst))

# MA-plot
tiff(file="MA.tiff",width=20,height = 20,units = "cm", compression = "lzw",bg="white",res=600)
par(mar=c(4,4,1,1), mfrow=c(1,1))
plot(
  log10(res$baseMean+1), res$log2FoldChange, xlab="Average read counts", ylab="log2fold(polyic/NC)",
  cex=.1, pch=19, col=alpha('grey',1), xaxt = "n", xlim=c(0,6), ylim=c(-10,15)
)
axis(1, at = 0:6, labels = 10^(0:6))
abline(h=0, lwd=3, col=alpha('#8B0000',1))
points(log10(res$baseMean[row.names(res) %in% up.lst]+1), res$log2FoldChange[row.names(res) %in% up.lst], cex=0.5, pch=19, col='#8B0000')
points(log10(res$baseMean[row.names(res) %in% dn.lst]+1), res$log2FoldChange[row.names(res) %in% dn.lst], cex=0.5, pch=19, col='#228B22')
dev.off()

pdf(file="MA.pdf",width=5,height = 5)
par(mar=c(4,4,1,1), mfrow=c(1,1))
plot(
  log10(res$baseMean+1), res$log2FoldChange, xlab="Average read counts", ylab="log2fold(polyic/NC)",
  cex=.1, pch=19, col=alpha('grey',0.5), xaxt = "n", xlim=c(0,6), ylim=c(-10,15)
)
axis(1, at = 0:6, labels = 10^(0:6))
abline(h=0, lwd=3, col=alpha('#FFB3B3',0.5))
points(log10(res$baseMean[row.names(res) %in% up.lst]+1), res$log2FoldChange[row.names(res) %in% up.lst], cex=0.3, pch=19, col='#FFB3B3')
points(log10(res$baseMean[row.names(res) %in% dn.lst]+1), res$log2FoldChange[row.names(res) %in% dn.lst], cex=0.3, pch=19, col='#B3FFB3')
dev.off()

## difgene_pheatmap
data_cpm <- log2(cpm(data)+1)
res.srt <- na.omit(res.srt)
res.srt$regulated <- "normal"
loc_up <- intersect(which(res.srt$log2FoldChange > 0),which(res.srt$padj < 0.05))
loc_down <- intersect(which(res.srt$log2FoldChange < 0),which(res.srt$padj < 0.05))
res.srt$regulated[loc_up] <- "up"
res.srt$regulated[loc_down] <- "down"
DEGSeq2_sigGene <- rownames(res.srt)[res.srt$regulated!="normal"]
DEGSeq2_sig <- res.srt[res.srt$regulated!="normal",]
dat1 <- data.frame(data_cpm[match(DEGSeq2_sigGene,rownames(data_cpm)),])
res.srt_1 <- as.data.frame(res.srt)
dat1$log2fc <- res.srt_1[match(rownames(dat1),rownames(res.srt_1)),]$log2FoldChange
write.csv(dat1, file = "DEGs_trna.csv")
dat2 <- dat1[,1:4]
P <- pheatmap(dat2,
         show_rownames = T,
         show_colnames = T,
         cluster_cols = F,
         cluster_rows=T,
         filename='de_pheatmap.tiff',
         fontsize_row=15, 
         fontsize_col=15,
         height=30,  
         width =6,
         scale = "row",
         angle_col=45, 
         color =colorRampPalette(c("#B3B3FF", "#E0E0E0","#FFB3B3"))(100),
         clustering_distance_rows = 'euclidean',
         clustering_method = 'single',
         cellwidth = 25,
         cellheight = 25
)
pheatmap(dat2,
         show_rownames = T,
         show_colnames = T,
         cluster_cols = F,
         cluster_rows=T,
         filename='de_pheatmap.pdf',
         fontsize_row=15, 
         fontsize_col=15,
         height=15,  
         width =6,
         scale = "row",
         angle_col=45, 
         color =colorRampPalette(c("#B3B3FF", "#E0E0E0","#FFB3B3"))(100),
         clustering_distance_rows = 'euclidean',
         clustering_method = 'single',
         cellwidth = 25,
         cellheight = 25
)
####log2fc
rowdata=rownames(dat2[p$tree_row[["order"]],])
dat3=dat1[match(rowdata, rownames(dat1)), ]
LOGFC <- dat3[,5]
rownames(LOGFC) <- "log2FC"
pheatmap(LOGFC,
         show_rownames = F,
         show_colnames = T,
         cluster_cols = F,
         cluster_rows=F,
         filename='de_pheatmap_logfc.tiff',
         fontsize_row=15, 
         fontsize_col=15,
         height=10,  
         width =6,
         # scale = "row",
         angle_col=45, 
         color =colorRampPalette(c("#B3B3FF", "#E0E0E0","#FFB3B3"))(100),
         clustering_distance_rows = 'euclidean',
         clustering_method = 'single',
         cellwidth = 25,
         cellheight = 25
)
